language: swift
osx_image: xcode9

branches:
  only:
  - master
  - dev

before_install:
  - gem install xcpretty -N
  - brew install swiftlint | true
script:
  - set -o pipefail
  - xcodebuild -workspace Logger.xcworkspace -scheme Logger -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  - xcodebuild -workspace Logger.xcworkspace -scheme Logger -destination "platform=iOS Simulator,name=iPhone 7,OS=latest" -sdk iphonesimulator test | xcpretty 
  - swiftlint